/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloaderRouteImport } from './routes/downloader'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiProxyDownloadRouteImport } from './routes/api.proxy-download'
import { Route as ApiPreviewRouteImport } from './routes/api.preview'
import { Route as ApiDownloadRouteImport } from './routes/api.download'

const DownloaderRoute = DownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyDownloadRoute = ApiProxyDownloadRouteImport.update({
  id: '/api/proxy-download',
  path: '/api/proxy-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreviewRoute = ApiPreviewRouteImport.update({
  id: '/api/preview',
  path: '/api/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloader': typeof DownloaderRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/proxy-download': typeof ApiProxyDownloadRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloader': typeof DownloaderRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/proxy-download': typeof ApiProxyDownloadRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloader': typeof DownloaderRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/preview': typeof ApiPreviewRoute
  '/api/proxy-download': typeof ApiProxyDownloadRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloader'
    | '/api/download'
    | '/api/preview'
    | '/api/proxy-download'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloader'
    | '/api/download'
    | '/api/preview'
    | '/api/proxy-download'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/downloader'
    | '/api/download'
    | '/api/preview'
    | '/api/proxy-download'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloaderRoute: typeof DownloaderRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiPreviewRoute: typeof ApiPreviewRoute
  ApiProxyDownloadRoute: typeof ApiProxyDownloadRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/downloader': {
      id: '/downloader'
      path: '/downloader'
      fullPath: '/downloader'
      preLoaderRoute: typeof DownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-download': {
      id: '/api/proxy-download'
      path: '/api/proxy-download'
      fullPath: '/api/proxy-download'
      preLoaderRoute: typeof ApiProxyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preview': {
      id: '/api/preview'
      path: '/api/preview'
      fullPath: '/api/preview'
      preLoaderRoute: typeof ApiPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloaderRoute: DownloaderRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiPreviewRoute: ApiPreviewRoute,
  ApiProxyDownloadRoute: ApiProxyDownloadRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
